version: '3'
services:
  app:
    build: .
    image: openjdk:17-jdk-alpine
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["java", "-jar", "/app/target/coding-api-0.0.1-SNAPSHOT.jar"]
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coding
    ports:
      - "3307:3306"
