version: 2.1

jobs:
  build-and-test:
    working_directory: ~/coding-api
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: coding
          POSTGRES_PASSWORD: 1234
    steps:
      - checkout:
          path: ~/coding-api
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

  generate-jacoco:
    working_directory: ~/coding-api
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout:
          path: ~/coding-api
      - run:
          name: Generate JaCoCo report
          command: mvn jacoco:report
      - run:
          name: List JaCoCo report directory
          command: ls target/site/jacoco
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco

workflows:
  sample:
    jobs:
      - build-and-test
      - generate-jacoco:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
