DELETE FROM LESSON;
DELETE FROM STUDENT;
DELETE FROM TEACHER_LANGUAGE;
DELETE FROM TEACHER;
DELETE FROM LANGUAGE;

ALTER TABLE LESSON AUTO_INCREMENT = 1;
ALTER TABLE LANGUAGE AUTO_INCREMENT = 1;
ALTER TABLE STUDENT AUTO_INCREMENT = 1;
ALTER TABLE TEACHER AUTO_INCREMENT = 1;
